name: Hexo Deploy

on:
  # workflow_run:
  #   workflows: [ scheduled-update ]
  #   types:
  #     - completed
  push:
    branches:
      - master
    paths:
      - 'source/**/*.md'
      - 'public/**/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    # Deploy hexo blog website.
    - name: Deploy
      env:
        GIT_USER: PttCodingMan
        GIT_EMAIL: pttcodingman@gmail.com
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "$GIT_USER"
        git config --global user.email "$GIT_EMAIL"
        npm run deploy -- -g
